spring:
  application:
    name: spring-security6-tutorial-03-jdbc
  datasource:
    url: jdbc:h2:mem:def
    username: sa
    password: 123456
  sql:
    init:
      schema-locations: classpath*:/sql/h2/schema.sql
      data-locations: classpath*:/sql/h2/data.sql